cleanup

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -17,6 +17,10 @@ jobs:
         with:
           submodules: recursive
 
+      # Unity is about 3gb in size and takes 20 minutes to download and install.
+      # Caching still takes some time, but brings it down to about 5 minutes.
+      # Note: if you change the installation step, remember to update the trailing
+      # hash at the end of the cache key.
       - name: Restore cached Unity installation
         id: cache-unity
         uses: actions/cache@v2
@@ -30,13 +34,36 @@ jobs:
           choco install unity-win-il2cpp --version ${{ env.UNITY_VERSION }} --yes --no-progress
         if: ${{ !steps.cache-unity.outputs.cache-hit }}
 
+      # Need to write to $GITHUB_PATH to make the environment variable
+      # available to other steps.
       - name: Add Unity on PATH
         run: |
           Write-Output "C:\Program Files\Unity\Editor" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
 
+      # License activation sometimes fails due to a problem connecting
+      # to Unity's licensing backend. Retry a few times if it fails.
       - name: Activate license
         run: |
-          unity -quit -batchmode -nographics -logFile - -serial ${{ secrets.UNITY_SERIAL }} -username ${{ secrets.UNITY_EMAIL }} -password ${{ secrets.UNITY_PASSWORD }} | Out-Default
+          $isSuccessful = False
+          $attempts = 5
+
+          while ($attempts -gt 0) {
+            try {
+              unity -quit -batchmode -nographics -logFile - -serial ${{ secrets.UNITY_SERIAL }} -username ${{ secrets.UNITY_EMAIL }} -password ${{ secrets.UNITY_PASSWORD }} | Out-Default
+
+              $isSuccessful = True
+              break
+            } catch {
+              Start-Sleep -Seconds 10
+            }
+
+            $attempts--
+          }
+
+          if (-not $isSuccessful) {
+            Write-Host "::error ::Failed to activate license after multiple attempts."
+            exit 1
+          }
 
       - name: Build project
         run: |
@@ -48,6 +75,7 @@ jobs:
           name: Build output
           path: ${{ env.PROJECT_PATH }}/artifacts/build
 
+      # This command doesn't work with the `-quit` option, unlike all the other ones
       - name: Run tests
         run: |
           unity -batchmode -nographics -logFile - -runTests -testPlatform StandaloneWindows64 -projectPath ${{ env.PROJECT_PATH }} -testResults artifacts/test/results.xml | Out-Default
@@ -58,6 +86,8 @@ jobs:
           name: Test results
           path: ${{ env.PROJECT_PATH }}/artifacts/test
 
+      # Running tests does not print anything useful to the console, nor does it fail
+      # the build, so we need to parse the results to figure out how things went.
       - name: Parse test results
         run: |
           $testRun = Select-Xml -Path ${{ env.PROJECT_PATH }}/artifacts/test/results.xml -XPath "/test-run" | Select-Object -Last 1
@@ -75,6 +105,7 @@ jobs:
             exit 1
           }
 
+      # Professional licenses are per-seat so we should always try to return them
       - name: Return license
         run: |
           unity -quit -batchmode -nographics -logFile - -returnlicense | Out-Default
