Test refactor

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -281,6 +281,7 @@ jobs:
           
       - name: Smoke test (Retry)
         id: smoke-test-retry
+        continue-on-error: true
         timeout-minutes: 10
         # We only want to retry the tests if the previous fail happened on the emulator startup.
         if: ${{ steps.smoke-test.outputs.smoke-started != 'yes' }}
@@ -294,12 +295,15 @@ jobs:
          force-avd-creation: false
          emulator-options:  -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
-         script: sudo pwsh ./scripts/smoke-test-droid.ps1
+         script:  |
+          echo "::set-output name=smoke-started::yes"
+          sudo pwsh ./scripts/smoke-test-droid.ps1
 
 
       - name: Throw error if Smoke test failed
-        # We want to throw an error if the smoke test failed
-        if: ${{ steps.smoke-test.outcome != 'success' && steps.smoke-test.outputs.smoke-started == 'yes' }}
+        # We want to throw an error if the smoke test failed.
+        # We will ignore flaky errors from the emulator setup.
+        if: ${{ (steps.smoke-test.outcome != 'success' && steps.smoke-test.outputs.smoke-started == 'yes') || (steps.smoke-test-retry.outcome != 'success' && steps.smoke-test-retry.outputs.smoke-started == 'yes') }}
         run: |
           exit -1
 
@@ -352,6 +356,7 @@ jobs:
 
       - name: Smoke test (Retry)
         id: smoke-test-retry
+        continue-on-error: true
         timeout-minutes: 10
         # We only want to retry the tests if the previous fail happened on the emulator startup.
         if: ${{ steps.smoke-test.outputs.smoke-started != 'yes' }}
@@ -371,8 +376,9 @@ jobs:
 
 
       - name: Throw error if Smoke test failed
-        # We want to throw an error if the smoke test failed
-        if: ${{ steps.smoke-test.outcome != 'success' && steps.smoke-test.outputs.smoke-started == 'yes' }}
+        # We want to throw an error if the smoke test failed.
+        # We will ignore flaky errors from the emulator setup.
+        if: ${{ (steps.smoke-test.outcome != 'success' && steps.smoke-test.outputs.smoke-started == 'yes') || (steps.smoke-test-retry.outcome != 'success' && steps.smoke-test-retry.outputs.smoke-started == 'yes') }}
         run: exit -1
 
       - name: Upload screenshot if smoke test failed
