fix: Bump Cocoa SDK for version `3` (#2371)

diff --git a/.github/workflows/sdk.yml b/.github/workflows/sdk.yml
--- a/.github/workflows/sdk.yml
+++ b/.github/workflows/sdk.yml
@@ -49,6 +49,8 @@ jobs:
         run: |
           if [[ "${TARGET}" == "Android" ]]; then
             submodules="modules/sentry-java"
+          elif [[ "${TARGET}" == "Cocoa" ]]; then
+            submodules=""
           else
             submodules="modules/sentry-native"
           fi
@@ -59,7 +61,13 @@ jobs:
       - name: Get submodule status
         run: git submodule status --cached ${{ steps.env.outputs.submodules }} | tee submodules-status
 
-      - run: cp -r package-dev/Plugins/${{ env.TARGET }} sdk-static || echo "never mind, no files checked in..."
+      - run: |
+          if [[ "${{ env.TARGET }}" == "Cocoa" ]]; then
+            cp -r package-dev/Plugins/iOS sdk-static/ || echo "never mind, no iOS files checked in..."
+            cp -r package-dev/Plugins/macOS sdk-static/ || echo "never mind, no macOS files checked in..."
+          else
+            cp -r package-dev/Plugins/${{ env.TARGET }} sdk-static || echo "never mind, no files checked in..."
+          fi
         shell: bash
 
       - name: Restore from cache
@@ -71,7 +79,7 @@ jobs:
           # hash of package/package.json for cache busting on release builds (version bump)
           path: |
             package-dev/Plugins
-          key: sdk=${{ env.TARGET }}-${{ hashFiles('submodules-status', 'package/package.json', 'Directory.Build.targets', 'sdk-static/**') }}
+          key: sdk=${{ env.TARGET }}-${{ hashFiles('submodules-status', 'package/package.json', 'Directory.Build.targets', 'sdk-static/**') }}${{ env.TARGET == 'Cocoa' && hashFiles('modules/sentry-cocoa.properties') || '' }}
 
       - name: Installing Linux Dependencies
         if: ${{ env.TARGET == 'Linux' && steps.cache.outputs.cache-hit != 'true' }}
@@ -92,7 +100,8 @@ jobs:
           dotnet msbuild /t:Build${{ env.TARGET }}SDK /p:Configuration=Release /p:OutDir=other src/Sentry.Unity
 
       - name: Upload build logs on failure
-        if: ${{ failure() }}
+        # No build logs for Cocoa SDK as we assemble the xcframework from a downloaded release artifact
+        if: ${{ failure() && env.TARGET != 'Cocoa' }}
         uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
         with:
           path: ${{ steps.env.outputs.submodulesPath }}/build.log
@@ -100,6 +109,17 @@ jobs:
           retention-days: 14
 
       - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
+        if: ${{ env.TARGET == 'Cocoa' }}
+        with:
+          name: ${{ env.TARGET }}-sdk
+          path: |
+            package-dev/Plugins/iOS/Sentry.xcframework~
+            package-dev/Plugins/macOS/Sentry
+          # Lower retention period - we only need this to retry CI.
+          retention-days: 14
+
+      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
+        if: ${{ env.TARGET != 'Cocoa' }}
         with:
           name: ${{ env.TARGET }}-sdk
           path: package-dev/Plugins/${{ env.TARGET }}
